[book]
title = "G9-Game-General"
authors = ["zeeqeen"]
description = "A project process standards for G9 Game General"
src = "src"
language = "zh"

[output.html]
git-repository-url = "https://github.com/zeeqeen/G9-book"